env:
<<<<<<< HEAD
  RUBY_VERSION: 2.7
  DB_ADAPTER: postgresql
  DB_HOST: localhost
  DB_NAME: postgres
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_PORT: 5432

name: CI
on:
  push:
    branches-ignore:
      - master
      - v1
      - v2
=======
  RUBY_VERSION: 3.1.0
  DATABASE_URL: postgres://postgres:postgres@localhost/greenlight-actions
  RAILS_ENV: test

name: CI
on:
>>>>>>> 5a3eb37130dbeeddf333366e83bfc929424877c8
  pull_request:
    branches: "*"

jobs:
  test:
<<<<<<< HEAD
    name: Rubocop + RSpec
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:13.2-alpine
=======
    name: Rubocop + RSpec + ESLint
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:13-alpine
>>>>>>> 5a3eb37130dbeeddf333366e83bfc929424877c8
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Health checks to wait until postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ruby ${{ env.RUBY_VERSION }}
<<<<<<< HEAD
        uses: actions/setup-ruby@v1
=======
        uses: ruby/setup-ruby@v1
>>>>>>> 5a3eb37130dbeeddf333366e83bfc929424877c8
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Bundle cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

<<<<<<< HEAD
      - name: Setup database
        run:  |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
=======
      - name: NPM install
        run: npm install

      - name: Setup database
        run: |
          bundler exec rails db:create
          bundler exec rails db:migrate
>>>>>>> 5a3eb37130dbeeddf333366e83bfc929424877c8

      - name: Run Rubocop
        run: bundle exec rubocop --parallel

      - name: Run RSpec
        run: bundle exec rspec
<<<<<<< HEAD
=======

      - name: Run ESLint
        run: npx eslint app/javascript/* --ext .js,.jsx
>>>>>>> 5a3eb37130dbeeddf333366e83bfc929424877c8
